### ISSUE TITLE
Неисправляемая ошибка

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#111]
Использовал вот эту версию РДО ebe40fbbe7f8fe309b07f5cfe4eebd4e36cd6339 (на момент написания таски - это `release/current`)

Создаём модель

``` java
enum BarberState {free, busy}

type BarberShop {
    BarberState barberState = BarberState.free;
    int queueLength = 0;
}
```

Запускаем. Модель отрабатывает с причиной `no more events`. Пока все хорошо. Меняем модель
`BarberState barberState = BarberState.free2;`
Сохраняем, запускаем, получаем ошибку. Пока все хорошо (сама ошибка полный отстой, ничего не понятно, надо смотреть исходники на java чтобы понять). Теперь возвращаем первоначальный вид, сохраняем, запускаем - ошибка осталась. Как это побороть ?

![2015-08-14 15 15 58](https://cloud.githubusercontent.com/assets/5585202/9273736/e639f7fe-4297-11e5-9beb-4c72bfa0d779.png)

**Comment by aurusov** [comment]
Возможно, причина в этом

```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at ru.bmstu.rk9.rao.ui.run.ExecutionHandler$2.run(ExecutionHandler.java:162)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: ru.bmstu.rk9.rao.lib.notification.NotifierException: Cannot remove subscriberru.bmstu.rk9.rao.ui.simulation.SimulationSynchronizer$SimulationManager$ScaleManager@279626e8, it is not present in subscription
    at ru.bmstu.rk9.rao.lib.notification.Subscription.removeSubscriber(Subscription.java:20)
    at ru.bmstu.rk9.rao.lib.notification.Notifier.removeSubscriber(Notifier.java:44)
    at ru.bmstu.rk9.rao.ui.notification.SimulatorSubscriberManager.unregisterExecutionSubscribers(SimulatorSubscriberManager.java:31)
    at ru.bmstu.rk9.rao.ui.notification.DefferedSubscriberManager$2.fireChange(DefferedSubscriberManager.java:46)
    at ru.bmstu.rk9.rao.lib.notification.Notifier.notifySubscribers(Notifier.java:26)
    at ru.bmstu.rk9.rao.lib.simulator.Simulator.setSimulationState(Simulator.java:46)
    at ru.bmstu.rk9.rao.lib.simulator.Simulator.initSimulation(Simulator.java:25)
    at rao_model.Embedded.initSimulation(Embedded.java:15)
    ... 6 more
```

**Comment by bogachev-pa** [comment]
Уже исправлено в ветке `2.3`.
Некорректно очищались подписки в случае ошибок прогона. Лечилось перезапуском плагина.
