### ISSUE TITLE
Ошибка запуска модели

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#157]
Итого, после обсуждений.
@bogachev-pa 
Есть три ошибки:
1. Путаница с перфиксами имен - https://github.com/aurusov/rdo-xtext/issues/33
2. Удаление src-gen и bin ведет к падению - https://github.com/aurusov/rdo-xtext/pull/167
3. Текущая таска - я понял причину, сломались дефолтные параметры

Модель не содержит ошибок, но не запускается

``` erlang
enum Положение {станок_1, станок_2, станок_3, накопитель_1, накопитель_2, тележка_1_н, тележка_1_к, тележка_2_н, тележка_2_к, нигде}

type Накопители {
    Положение положение;
    int номер;
    int максимальное_количество = 25;
    int текущее_количество = 0;
}

enum Состояние_тележки {свободен, занят, загружен, перемещается, прибыл, ожидает} 
type Тележки {
    int номер;
    Положение положение;
    Состояние_тележки состояние = Состояние_тележки.свободен;
}

enum Состояние_робота {свободен, занят}
type Роботы {
    int номер;
    Положение положение;
    Состояние_робота состояние = Состояние_робота.свободен;
}

enum Состояние_станка {свободен, загружается, готов_к_обработке, работает,разгружается, закончил_обработку}
type Станки {
    int номер;
    Положение положение;
    Состояние_станка состояние = Состояние_станка.свободен;
    double длительность_обработки;
}

enum Состояние_детали {хранится, транспортируется, обрабатывается, обработка_закончна}
type Детали {
    int номер;
    Положение положение = Положение.накопитель_1;
    Состояние_детали состояние = Состояние_детали.хранится;
}
```

```
Java Model Exception: Java Model Status [Build path contains duplicate entry: 'C:git/rdo-xtext/ru.bmstu.rk9.rao.lib/bin/' for project 'fms_laba']
    at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:785)
    at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3097)
    at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3059)
    at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3112)
    at ru.bmstu.rk9.rao.ui.build.ModelBuilder.checkProjectClassPath(ModelBuilder.java:131)
    at ru.bmstu.rk9.rao.ui.build.ModelBuilder.access$0(ModelBuilder.java:98)
    at ru.bmstu.rk9.rao.ui.build.ModelBuilder$1.run(ModelBuilder.java:193)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at ru.bmstu.rk9.rao.ui.run.ExecutionHandler$2.run(ExecutionHandler.java:169)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: ru.bmstu.rk9.rao.lib.json.JSONException: JSONObject["structure"] not found.
    at ru.bmstu.rk9.rao.lib.json.JSONObject.get(JSONObject.java:478)
    at ru.bmstu.rk9.rao.lib.json.JSONObject.getJSONObject(JSONObject.java:578)
    at ru.bmstu.rk9.rao.lib.database.Database.<init>(Database.java:97)
    at ru.bmstu.rk9.rao.lib.simulator.Simulator.initSimulation(Simulator.java:31)
    at rao_model.Embedded.initSimulation(Embedded.java:15)
    ... 6 more

!ENTRY ru.bmstu.rk9.rao.ui 4 0 2015-09-13 21:13:40.920
!MESSAGE Execution failed
!STACK 0
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at ru.bmstu.rk9.rao.ui.run.ExecutionHandler$2.run(ExecutionHandler.java:169)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: ru.bmstu.rk9.rao.lib.json.JSONException: JSONObject["structure"] not found.
    at ru.bmstu.rk9.rao.lib.json.JSONObject.get(JSONObject.java:478)
    at ru.bmstu.rk9.rao.lib.json.JSONObject.getJSONObject(JSONObject.java:578)
    at ru.bmstu.rk9.rao.lib.database.Database.<init>(Database.java:97)
    at ru.bmstu.rk9.rao.lib.simulator.Simulator.initSimulation(Simulator.java:31)
    at rao_model.Embedded.initSimulation(Embedded.java:15)
    ... 6 more
Root exception:
ru.bmstu.rk9.rao.lib.json.JSONException: JSONObject["structure"] not found.
    at ru.bmstu.rk9.rao.lib.json.JSONObject.get(JSONObject.java:478)
    at ru.bmstu.rk9.rao.lib.json.JSONObject.getJSONObject(JSONObject.java:578)
    at ru.bmstu.rk9.rao.lib.database.Database.<init>(Database.java:97)
    at ru.bmstu.rk9.rao.lib.simulator.Simulator.initSimulation(Simulator.java:31)
    at rao_model.Embedded.initSimulation(Embedded.java:15)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at ru.bmstu.rk9.rao.ui.run.ExecutionHandler$2.run(ExecutionHandler.java:169)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by aurusov** [comment]
Очень неудобно писать модель, когда IDE не говорит, почему ошибка :(
Не понимаю, как такое отдавать студентам :(

**Comment by bogachev-pa** [comment]
Выглядит, как внутренняя ошибка. Посмотрю.

**Comment by aurusov** [comment]
Проект и файл модели названы одинаково. М.б. в этом проблема.

![2015-09-13 21-21-38 rao - fms_laba fms_laba rao - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/9838123/8b02946c-5a5d-11e5-8ccf-bb492d3ea426.png)

**Comment by bogachev-pa** [comment]
> Проект и файл модели названы одинаково. М.б. в этом проблема.

Даже есть таска. https://github.com/aurusov/rdo-xtext/issues/33
Но я не ожидал таких фатальных последствий.

**Comment by aurusov** [comment]
Переименовал `fms_laba.rao` -> `fms.rao`. Не помогло.

**Comment by aurusov** [comment]
Тот же

```
Caused by: ru.bmstu.rk9.rao.lib.json.JSONException: JSONObject["structure"] not found.
```

**Comment by aurusov** [comment]
Закрыл оба Эклипса, удалил папки `bin` и `src-gen`, перезапустил Эклипсы. Получил

```
Java Model Exception: Java Model Status [Build path contains duplicate entry: 'C:git/rdo-xtext/ru.bmstu.rk9.rao.lib/bin/' for project 'fms_laba']
    at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:785)
    at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3097)
    at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3059)
    at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3112)
    at ru.bmstu.rk9.rao.ui.build.ModelBuilder.checkProjectClassPath(ModelBuilder.java:131)
    at ru.bmstu.rk9.rao.ui.build.ModelBuilder.access$0(ModelBuilder.java:98)
    at ru.bmstu.rk9.rao.ui.build.ModelBuilder$1.run(ModelBuilder.java:193)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
java.lang.ClassNotFoundException: rao_model.Embedded
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at ru.bmstu.rk9.rao.ui.run.ExecutionHandler$2.run(ExecutionHandler.java:145)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY ru.bmstu.rk9.rao.ui 4 0 2015-09-13 21:39:30.649
!MESSAGE Execution failed
!STACK 0
java.lang.ClassNotFoundException: rao_model.Embedded
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at ru.bmstu.rk9.rao.ui.run.ExecutionHandler$2.run(ExecutionHandler.java:145)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by bogachev-pa** [comment]
Если удалить обе папки все падало, да, это несвязанная ошибка, починится визардом.

**Comment by aurusov** [comment]
1. Что с моделью делать-то ?
2. Если ошибки не связаны, то одну таску ты привел. Вторая есть или текущая сойдёт ?

**Comment by bogachev-pa** [comment]
Есть три ошибки:
1. Путаница с перфиксами имен - привел таску.
2. Удаление src-gen и bin ведет к падению - решается, вероятно, визардом.
3. Эта проблема - я понял причину, сломались дефолтные параметры, можете пока отлаживать модель без них, я смотрю, где именно сломались.

Новые таски заводить не нужно.

**Comment by bogachev-pa** [comment]
3**.** Починил.

**Comment by bogachev-pa** [comment]
2**.** Тоже починил.

Остался пункт 1 - под него есть отдельная таска.

**Comment by bogachev-pa** [comment]
2**.** Зачинил окончательно. (:

**Comment by bogachev-pa** [comment]
Под пункт 1 есть отдельная задача, остальное замержено, закрываю.
