### ISSUE TITLE
Ошибка запуска пустой процессной модели

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#412]
Создать модель визардом, добавить пустую процессную модель `New -> File -> test.proc`, запустить.

![2016-07-10_17-39-10](https://cloud.githubusercontent.com/assets/5585202/16714241/6143abd4-46c5-11e6-889b-d1cf6a01e752.png)

```
java.io.EOFException
    at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
    at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
    at java.io.ObjectInputStream.<init>(Unknown Source)
    at ru.bmstu.rk9.rao.ui.process.ProcessEditor.readModelFromFile(ProcessEditor.java:403)
    at ru.bmstu.rk9.rao.ui.execution.ModelInternalsParser.postprocess(ModelInternalsParser.java:264)
    at ru.bmstu.rk9.rao.ui.execution.ExecutionJobProvider$1.run(ExecutionJobProvider.java:68)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY ru.bmstu.rk9.rao.ui 4 0 2016-07-10 17:38:50.998
!MESSAGE Model postprocessing failed
!STACK 0
java.io.EOFException
    at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
    at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
    at java.io.ObjectInputStream.<init>(Unknown Source)
    at ru.bmstu.rk9.rao.ui.process.ProcessEditor.readModelFromFile(ProcessEditor.java:403)
    at ru.bmstu.rk9.rao.ui.execution.ModelInternalsParser.postprocess(ModelInternalsParser.java:264)
    at ru.bmstu.rk9.rao.ui.execution.ExecutionJobProvider$1.run(ExecutionJobProvider.java:68)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by kobzarvlad** [comment]
Добрый вечер!
Хотел бы взять эту задачу. Кобзарь Влад, РК9-82

**Comment by aurusov** [comment]
Берите
