### ISSUE TITLE
Не запускается release/current

### ISSUE THREAD

**Issue by aurusov** [LeKaitoW/raox#92]
Под виндой.

![2015-07-12 21-12-33 rao - barber barber rao - eclipse platform](https://cloud.githubusercontent.com/assets/5585202/8639190/ce80cf56-28da-11e5-8a05-966e7f157e4b.png)

```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at ru.bmstu.rk9.rao.ui.run.ExecutionHandler$2.run(ExecutionHandler.java:181)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: ru.bmstu.rk9.rao.lib.database.DatabaseException: Unexpected result type: watchState
    at ru.bmstu.rk9.rao.lib.database.Database$ResultType.get(Database.java:648)
    at ru.bmstu.rk9.rao.lib.database.Database.<init>(Database.java:105)
    at ru.bmstu.rk9.rao.lib.simulator.Simulator.initDatabase(Simulator.java:45)
    at rao_model.Embedded.initSimulation(Embedded.java:16)
    ... 6 more

!ENTRY ru.bmstu.rk9.rao.ui 4 0 2015-07-12 21:11:57.796
!MESSAGE Execution failed
```

**Comment by aurusov** [comment]
Ты поменял ключевые слова для собираемых показателей ? Не могу найти в каком коммите. Если да, то покажи где и измени примеры моделей.

**Comment by aurusov** [comment]
Или наоборот, ты забыл подлить эти изменения ?

**Comment by aurusov** [comment]
Нашел https://github.com/bogachev-pa/rdo-xtext/commit/769b81a76c9b2de6213132271be220b76a99f085.

**Comment by aurusov** [comment]
Выпустил релиз 2.1.1, проблема ушла.

**Comment by bogachev-pa** [comment]
Если вкратце, но коммит с выбрасывание исключений вместо возврата `null` вскрывал проблему более явно (раньше просто пропадали записи в трассировках и, наверное, не строились бы графики) и совсем крашил прогон.
Багфикс был в ветке `2.1`, все правильно.

Видимо, такие багфиксы надо заливать сразу, но я что-то запутался в гитфлоу как раз на нем.

**Comment by aurusov** [comment]
Как я понял, это вылезло из-за изменений в рефакторинге. Мне кажется, что исправлять это место было там же, а не в отдельной ветке.

**Comment by bogachev-pa** [comment]
Изменения в грамматике привели к этой ошибке, а рефакторинг с эксепшенами ее вскрыл. Почему-то я сразу не заметил, когда рефакторил эксепшены, и в итоге уже замержил их в релиз/карент. Потому и создал ветку отдельно.
